fix(#1100): empty file resource returns true on exist
citrusframework/citrus pull request #1114
Opened 2024-01-29 12:59 UTC by tschlat

Fixes issue #1100:
An UrlResource pointing to an existing but empty file must return true on exist.

Also added a couple of tests.

2024-01-29 13:18 UTC, bbortt requested changes
thank you very much! looks good to me in general, only some nitpicks.

2024-01-29 13:18 UTC, bbortt commented on core/citrus-api/src/main/java/org/citrusframework/spi/Resources.java
> +
```suggestion
```

please do also update the copyright year to `2023-2024` on top of this class.

2024-01-29 13:18 UTC, bbortt commented on core/citrus-api/src/test/java/org/citrusframework/spi/ResourcesTest.java
> +public class ResourcesTest {
this file is not properly formatted.

2024-01-29 13:24 UTC, tschlat reviewed
Done

2024-01-29 17:36 UTC, bbortt commented
> Done

well thank you!

2024-01-29 17:37 UTC, bbortt approved these changes

2024-01-31 19:14 UTC, christophd approved these changes
Awesome!

2024-01-31 19:14 UTC, merged