Adds new changes to main #1175 Branch: OpenApiRepository and Validation
citrusframework/citrus pull request #1179
Opened 2024-06-21 06:18 UTC by tschlat

Implement new features:
- a repository for OpenApis
- validation based on atlassian OpenAPI validator framework

2024-06-24 16:33 UTC, bbortt commented
> We should make a decision on how to proceed here:

I am personally ok with "hardening" features when it comes to **feature releases** - which it is.

> The later is much more powerfull but might raise more issues.

I don't think that has to be breaking necessarily, as long as the API itself (e.g. OpenAPI must be stored in a different directory, leading to false-positives because no spec is loaded at all) does not break.

2024-06-24 17:20 UTC, bbortt requested changes
not an easy one! well done @tschlat. especially the reported coverage on `citrus-openapi`:

![image](https://github.com/citrusframework/citrus/assets/12272901/3b93f34a-6db6-43f3-af19-adafd43fb079)

I took the freedom to commit some minor adjustments. nothing big, overall.

I've also questioned some code parts, but only one or two.

2024-06-24 17:20 UTC, bbortt commented on connectors/citrus-openapi/src/main/java/org/citrusframework/openapi/actions/OpenApiClientRequestActionBuilder.java
> +    public OpenApiClientRequestActionBuilder disableOasValidation(boolean b) {
since this method is called "disable" I would just assume it disables validation (no matter what). I would not expect a parameter for sure. thoughts?

2024-06-24 17:20 UTC, bbortt commented on connectors/citrus-openapi/src/main/java/org/citrusframework/openapi/model/OasAdapter.java
> +public class OasAdapter<S extends Node, T> {
this is a record as well. I've updated it:

```java
public record OasAdapter<S extends Node, T>(S node, T adapted) {

}
```

or do you intend to overwrite it somewhere?

2024-06-24 17:20 UTC, bbortt commented on connectors/citrus-openapi/src/main/java/org/citrusframework/openapi/model/v2/Oas20ModelHelper.java
> +        return Arrays.asList("application/x-www-form-urlencoded", "multipart/form-data").contains(type);
out of curiosity, where did you get these from? because there exist more, I think. at least some `message/*` things.

2024-06-24 17:20 UTC, bbortt commented on connectors/citrus-openapi/src/main/java/org/citrusframework/openapi/validation/OpenApiRequestValidator.java
> +            if (value instanceof Collection<?>) {
I've changed this to:

```suggestion
            if (value instanceof Collection<?> collection) {
```

2024-06-24 17:20 UTC, bbortt commented on connectors/citrus-openapi/src/test/java/org/citrusframework/openapi/OpenApiTestDataGeneratorTest.java
> +    // TODO: fix this by introducing mature validation
what about these? are these to be based on the decision?

2024-06-24 17:20 UTC, bbortt commented on core/citrus-base/src/main/java/org/citrusframework/util/StringUtils.java
> +    public static String appendSegmentToUrlPath(String path, String segment) {
should be non breaking, I think:

```java
    @Deprecated(forRemoval = true)
    public static String appendSegmentToPath(String path, String segment) {
        appendSegmentToUrlPath(path, segment);
    }

    public static String appendSegmentToUrlPath(String path, String segment) {
```

2024-06-24 17:36 UTC, bbortt commented on core/citrus-base/src/main/java/org/citrusframework/util/StringUtils.java
> +    public static String appendSegmentToUrlPath(String path, String segment) {
(I have _not_ updated this)

2024-06-24 18:31 UTC, bbortt commented on connectors/citrus-openapi/src/main/java/org/citrusframework/openapi/actions/OpenApiServerActionBuilder.java
> +        if (referenceResolver != null) {
see https://github.com/citrusframework/citrus/pull/1184.

2024-06-25 06:28 UTC, tschlat commented on connectors/citrus-openapi/src/main/java/org/citrusframework/openapi/OpenApiSpecificationAdapter.java
> +public class OpenApiSpecificationAdapter<T> {
No it's OK. I had this in mind but overcome it somehow.

2024-06-30 07:56 UTC, bbortt approved these changes

2024-06-30 07:56 UTC, merged