kafka concurrent access
citrusframework/citrus pull request #1282
Opened 2024-12-17 18:20 UTC by bbortt

closes #1281.

2024-12-17 18:37 UTC, bbortt commented
> @[bbortt](https://github.com/bbortt) bbortt requested review from [tschlat](https://github.com/tschlat) and [christophd](https://github.com/christophd) and removed request for [tschlat](https://github.com/tschlat)

ah yea, that makes sense 💃🏼 my clicking is way too fast for GitHub.

2025-01-06 11:06 UTC, tschlat requested changes

2025-01-08 12:17 UTC, bbortt commented
@tschlat I've now added a flag `useThreadSafeConsumer`... that makes it backwards compatible.

2025-01-08 14:12 UTC, christophd approved these changes

2025-01-09 07:29 UTC, merged